### ISSUE TITLE
options.setHeaders not called when serving compressed files

### ISSUE THREAD

**Issue by michael42** [pirxpilot/connect-gzip-static#15]
It seems that connect-gzip-static doesn't call the `options.setHeaders` callback when serving the compressed files as serve-static would do. When requesting the uncompressed files (such as testing with curl or wget's default options), `setHeaders` is called.

To reproduce, you can run the following:
````
const http = require("http");
const fs = require("fs");
const express = require("express");
const gzipStatic = require("connect-gzip-static");

fs.writeFileSync("1", "content of 1");
fs.writeFileSync("1.gz", "content of 1.gz");

const app = express();
app.use("/", gzipStatic(".", {
    setHeaders: res => res.setHeader("X-Testing-If-Header-Is-Set", "true")
}));

http.createServer(app).listen(1234);
````

And compare these responses:
````
$ curl --verbose 'http://localhost:1234/1' -H 'accept-encoding: gzip'
[...]
< HTTP/1.1 200 OK
< X-Powered-By: Express
[...]
````

````
$ curl --verbose 'http://localhost:1234/1'
[...]
< HTTP/1.1 200 OK
< X-Powered-By: Express
< X-Testing-If-Header-Is-Set: true
[...]
````

Apparently someone else noticed and [fixed it in a fork](https://github.com/gitsumanth/connect-gzip-static/commit/3108475330434b76d916bbceef22251aa51ee93d).

**Comment by pirxpilot** [comment]
fixed in 2.1.1
thanks for reporting!
